# Generated by Django 4.2 on 2023-04-28 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_lists', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todolist',
            name='completion_at',
            field=models.DateTimeField(blank=True),
        ),
    ]
