# Generated by Django 4.2 on 2023-04-28 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_lists', '0002_alter_todolist_completion_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todolist',
            name='completion_at',
            field=models.DateTimeField(blank=True, verbose_name='할일 완료 시간'),
        ),
        migrations.AlterField(
            model_name='todolist',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='할일 생성 시간'),
        ),
        migrations.AlterField(
            model_name='todolist',
            name='is_complate',
            field=models.BooleanField(default=False, verbose_name='완료 여부'),
        ),
        migrations.AlterField(
            model_name='todolist',
            name='title',
            field=models.CharField(max_length=100, verbose_name='할일 제목'),
        ),
        migrations.AlterField(
            model_name='todolist',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='할일 마지막 수정 시간'),
        ),
    ]
