# Generated by Django 4.2 on 2023-04-28 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_lists', '0003_alter_todolist_completion_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todolist',
            name='completion_at',
            field=models.DateTimeField(null=True, verbose_name='할일 완료 시간'),
        ),
    ]
